### ISSUE TITLE
CI on the blog site

### ISSUE THREAD

**Issue by tsaoyu** [Maritime-Robotics-Student-Society/blog#1]
Create continuous integration files for the blog site

**Comment by alvaropp** [comment]
https://gist.github.com/domenic/ec8b0fc8ab45f39403dd

**Comment by tsaoyu** [comment]
Thank you @alvaropp I have followed the instruction you provided. But it seems build [#21](https://travis-ci.org/Maritime-Robotics-Student-Society/blog#L715) is still failed because permission issue. But `ssh` welcome information shows in [#20](https://travis-ci.org/Maritime-Robotics-Student-Society/blog/builds/202072084#L713) seems good. I suspect this protocol (`https`,`git@github.com`) related issue mentioned on [stack](http://stackoverflow.com/a/34081606/4941207). 

I have setup [ssh key](https://github.com/Maritime-Robotics-Student-Society/blog/settings/keys) for this repository just one more step to go.

**Comment by tsaoyu** [comment]
@takluyver point me out that I haven't give write access to the `ssh` key pair. 
Now the CI should able to automatic build pages and push it back to `gh-pages`.

**Comment by alvaropp** [comment]
nice!
